### ISSUE TITLE
view > landmark colors

### ISSUE THREAD

**Issue by arobie** [kristinbranson/APT#295]
trying to manually adjust colors seems to freeze project irreversibly

**Comment by arobie** [comment]
maybe this ....
Warning: The following error was caught while executing 'matlab.ui.internal.dialog.WebColorChooser' class destructor:
Error using matlab.ui.internal.dialog.WebColorChooser/delete (line 60)
Java exception occurred:
com.teamdev.jxbrowser.chromium.internal.ipc.IPCException: Failed to execute shutdown post message.
	at com.teamdev.jxbrowser.chromium.internal.ipc.IPC.c(Unknown Source)
	at com.teamdev.jxbrowser.chromium.internal.ipc.IPC.stop(Unknown Source)
	at com.teamdev.jxbrowser.chromium.Browser.a(Unknown Source)
	at com.teamdev.jxbrowser.chromium.Browser.dispose(Unknown Source)
	at com.mathworks.html.jxbrowser.chromium.LightweightChromiumBrowser.dispose(LightweightChromiumBrowser.java:138)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.mathworks.jmi.AWTUtilities$Invoker$3$1.call(AWTUtilities.java:525)
	at com.mathworks.mvm.context.ThreadContext.callWithContext(ThreadContext.java:105)
	at com.mathworks.mvm.context.MvmContext.callWithContext(MvmContext.java:113)
	at com.mathworks.jmi.AWTUtilities$Invoker$3.runWithOutput(AWTUtilities.java:522)
	at com.mathworks.jmi.AWTUtilities$Invoker$2.watchedRun(AWTUtilities.java:475)
	at com.mathworks.jmi.AWTUtilities$WatchedRunnable.run(AWTUtilities.java:436)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Error in uisetcolor_helper (line 3)
[rgbColorVector,title,fhandle] = parseArgs(varargin{:});

Error in uisetcolor (line 37)
selectedColor = uisetcolor_helper(varargin{:});

Error in LandmarkColors>pushbutton_manual_Callback (line 301)
handles.colors(landmarki,:) = uisetcolor(handles.colors(landmarki,:),sprintf('Landmark %d color',landmarki));

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in LandmarkColors (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in LandmarkColors>@(hObject,eventdata)LandmarkColors('pushbutton_manual_Callback',hObject,eventdata,guidata(hObject),i) (line 175)
    'Callback',@(hObject,eventdata)LandmarkColors('pushbutton_manual_Callback',hObject,eventdata,guidata(hObject),i),... 
> In uisetcolor_helper (line 3)
  In uisetcolor (line 37)
  In LandmarkColors>pushbutton_manual_Callback (line 301)
  In gui_mainfcn (line 95)
  In LandmarkColors (line 42)
  In LandmarkColors>@(hObject,eventdata)LandmarkColors('pushbutton_manual_Callback',hObject,eventdata,guidata(hObject),i) (line 175)
  In uiwait (line 81)
  In LandmarkColors>LandmarkColors_OpeningFcn (line 190)
  In gui_mainfcn (line 220)
  In LandmarkColors (line 40)
  In LabelerGUI>menu_view_landmark_label_colors_Callback (line 4082)
  In gui_mainfcn (line 95)
  In LabelerGUI (line 33)
  In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)LabelerGUI('menu_view_landmark_label_colors_Callback',hObject,eventdata,guidata(hObject)) 
Error using matlab.ui.Figure/set
Invalid or deleted object.

Error in matlab.hg.internal.openfigLegacy (line 117)
                set(fig,'Visible',savedvisible);

Error in gui_mainfcn>local_openfig (line 286)
    gui_hFigure = matlab.hg.internal.openfigLegacy(name, singleton, visible);

Error in gui_mainfcn (line 233)
            gui_hFigure = local_openfig(gui_State.gui_Name, 'reuse',gui_Visible);

Error in LandmarkColors (line 40)
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});

Error in LabelerGUI>menu_view_landmark_label_colors_Callback (line 4082)
  LandmarkColors(colors,colormapname,nlandmarks,'Label colors',applyCbkFcn);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in LabelerGUI (line 33)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)LabelerGUI('menu_view_landmark_label_colors_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating Menu Callback.

**Comment by allenleetc** [comment]
hopefully fixed by new cosmetics picker under View>

**Comment by arobie** [comment]
cosmetic picker works great so far!
It would be super helpful if predictions and imported predictions could be modified separately. I think right now they are basically the same? and its hard to compare.

**Comment by allenleetc** [comment]
yes they are the same atm. 

in general with imported/comparisons, i'm concerned do we have a handle on all the workflow(s)? esp since we currently do not save tracking results in the proj. using imported seems to address this workflow: "i have standard/baseline results in a trkfile that i want to compare transient results against. eg maybe i am experimenting with trackers and parameters etc." 

what about these:
- i want to do a pairwise comparison of transient (nonexported) results -- eg trackerA and trackerB. (can always workaround by exporting one set)
- i want to do a pairwise comparison where both are exported. (this may occur more often since we don't save tracking results in projs)
- i want to compare 3+ sets of results
